# namespace is required to be used with dcao-includes which will pull in external docker-compose files
namespace: opsdroid
services:

  opsdroid:
    ports:
    - "8080:8080"
    links:
    - jenkins:jenkins

  jenkins:
    container_name: jenkins
    image: jenkins:latest
    volumes:
      - "~/.jenkins_home/:/var/jenkins_home"
    expose:
      - "8081"
    ports:
      - "8081:8080"
    restart: "always"

  mail:
    container_name: mail
    image: namshi/smtp
    ports:
      - '10025:25'
version: '2'

