version: '2'
services:

  namespace: jenkins

  core.opsdroid:
    ports:
    - "8080:8080"
    links:
    - jenkins:jenkins

  jenkins.jenkins:
    container_name: jenkins
    image: jenkins:latest
    volumes:
      - "~/.jenkins_home/:/var/jenkins_home"
    expose:
      - "8081"
    ports:
      - "8081:8080"
    restart: "always"

  jenkins.mail:
    container_name: mail
    image: namshi/smtp
    ports:
      - '10025:25'